### ISSUE TITLE
Communication is heard through all the channels

### ISSUE THREAD

**Issue by ouin10** [Larkooo/FrequencyWalkie#6]
Currently using a modpack I created with every mod being compatible with eachother. The list of mods is in the image.
![Screenshot_1](https://github.com/Larkooo/FrequencyWalkie/assets/32625779/d4eef5dc-3a01-43f5-871a-0d08ec94c356)

Using these mods while using the FrequencyWalkie mod, you can hear people talk across all channels no matter what channel you are on.
If I am on channel (example) 19.2 and my friend is on 40.1, they both can talk to eachother.
This was both tested at the company building, in orbit and on moons.

**Comment by Larkooo** [comment]
Do you guys have any other mods that mess with the walkie talkie? FrequencyWalkie patches the walkie-talkie related rpc handlers so if any other mod does the same thing or transmits voices on their own then this mod won't work. As the patched methods effectively block incoming transmissions depending on the frequency you're currently on. From quickly taking a glance at your mod list, I'm thinking maybe VoiceHUD or any other voice related mod has something to do with that

**Comment by ouin10** [comment]
Alright, it might be something like VoiceHUD yeah. Thank you though
